# -----[Color Theme]-----
include  themes/gruvbox_light.conf

# -----[Fonts]-----
font_family      FiraCode Nerd Font
bold_font        FiraCode Nerd Font
italic_font      JetBrains Mono Nerd Font
bold_italic_font JetBrains Mono Nerd Font
font_size 13.0

# -----[Keybinds]-----
map ctrl+backspace send_text all \x17

# -----[Other Settings]-----
# cursor_trail 1
enable_audio_bell no
window_padding_width 10

# Apenas defina o estilo customizado. O Kitty buscará o script 
# automaticamente se ele estiver no caminho correto (veja o Passo 3).
tab_bar_style custom
tab_bar_min_tabs 1
tab_bar_align center

# Garante um título limpo (apenas o que o shell envia).
tab_title_template "{title}"
tab_title_with_windows no

# -----[Vim Slime]-----
allow_remote_control yes
listen_on unix:/tmp/mykitty
